version: "3.8"

services:

  # nexus:
  #   image: sonatype/nexus3:3.75.1-java17-alpine
  #   container_name: nexus
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./volumes/nexus-data:/nexus-data
  #   networks:
  #     - network
  #   restart: unless-stopped
  #   environment:
  #     INSTALL4J_ADD_VM_PARAMS: "-Xms2g -Xmx4g -Dsonatype.skip.malicious-risk-on-disk=true"  # Deshabilitar la tarea

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    command: >
      start-dev
      --http-port=8080
      --import-realm
    networks:
      - network
    volumes:
      - './dockerVolumes/keycloak_data:/data'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

networks:
  network:
    driver: bridge